### PR TITLE
Linter: fix linter exception logging

### LINKED ISSUE #16785: Unneeded linter exceptions check will display obsolete exceptions when specifying custom fileset
Recently, the ability to add exceptions to linters was implemented, so that linters may allow failures for specific features or files.  Any obsolete exceptions will also be reported if the lint for a specific feature/file _should_ fail, but doesn't.

However, if a custom scope of files is specified when running the lint command (ex. `npm run lint api/AbortController.json`), any features that were not present in the specified file will not throw an error, thus it gets reported as an obsolete exception.

CC @bershanskiy

### PR DESCRIPTION
**Pull request by bershanskiy**
#### Summary

#16740 added a message about linter exceptions, but contained a bug described in #16785. This PR:
 - fixes said bug
 - makes existence of known unnecessary exceptions into a lint error (previously it was just a log statement)

#### Test results and supporting details

Ran `npm run lint` and `npm run lint api/AbortController.json` and observed expected output. Then added an unneeded exception `api.AbortController` and ran these commands again and observed expected lint failure.

#### Related issues

Fixes #16785.

### CODE REVIEW

File: test/lint.ts [hunk 1]
```diff
@@ -187,12 +187,15 @@ const main = async (
   // Find all unnecessary linting exceptions
   for (const linter of linters.linters) {
     if (linter.exceptions) {
-      const actual = new Set(linters.expectedFailures[linter.name]);
-      for (const exception of linter.exceptions)
-        if (!actual.has(exception))
+      const missingExceptions = linters.missingExpectedFailures[linter.name];
+      for (const exception in missingExceptions) {
+        if (missingExceptions[exception]) {
+          hasErrors = true;
```
Comment (bershanskiy) [inline test/lint.ts:193]: I think unnecessary exceptions should be treated as a lint error, but will be glad to revert this if needed.

**Review by queengooborg — APPROVED** [review]
Thanks for tackling this, this is LGTM!
