### PR TITLE
Convert remove-redundant-flags script into linter and fixer

### LINKED ISSUE #20801: Make `remove-redundant-flags` part of linting
### What type of issue is this?

Infrastructure issue

### What is the issue?

I reviewed quite a few PRs that fix the output of `remove-redundant-flags`. We should remove the remaining redundant flags and make CI fail if new redundant flags are introduced.

### What behavior were you expecting?

CI fails if new redundant flags are in the data. 
We won't need to review cleanup PRs for this in the future anymore.

### What version(s) of BCD is the issue present in?

- [ ] The current BCD release
- [ ] The current version of the `main` branch

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by queengooborg**
This PR converts the `remove-redundant-flags` script into a linter and a fix script, so that unneeded flag data can be enforced programmatically.  Some logic for catching invalid flags has also been updated to catch additional cases.  Note that this will _fail_ the CI because we currently have data that violates the linter rule.

Fixes #20801.

### CODE REVIEW

File: test/linter/test-flags.ts [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+  check: (logger: Logger, { data }: LinterData) => {
+    const errors = processData(data);
+
+    for (const error of errors) {
+      logger.error(
+        chalk`Irrelevant flag data detected for {bold ${
+          error.browser
+        }}. Remove statement for ${error.flagData
+          .map((flag) => flag.name)
+          .join(', ')}`,
```
Comment (Elchi3) [inline test/linter/test-flags.ts:158]:
```suggestion
        }}. Remove statement with {bold ${error.flagData
          .map((flag) => flag.name)
          .join(', ')}} flag`,
```

**Review by Elchi3 — APPROVED** [review]
Thanks for turning this into a lint! Looks great to me and the actual flag checking seems well tested already, so that's good. I have just one minor nit with the lint message.

**Comment by Elchi3** [comment]
Fixes https://github.com/mdn/browser-compat-data/issues/20801
