### PR TITLE
Throw a better-worded error when duplicate features found

### LINKED ISSUE #10734: BCD loader crashes when mixin feature included in both files
When working on #10724, I ran into an issue where the `extend()` function in `index.js` crashes, throwing an error that `"Both target and source must be plain objects"`.  After doing some research, I was able to determine two causes for this error.  The first is due to invisible files created by the system (which I've addressed in #10733).  The second is a little more troublesome, which is why I'm opening this issue.

The reason behind this boils down to two separate files containing the exact same feature.  While demixing `LinkStyle`, I hadn't noticed that the feature it exposes on `HTMLStyleElement`was also documented in the dedicated API's JSON, so when creating the new mixin file, both `api/HTMLStyleElement.json` and `api/_mixins/LinkStyle__HTMLStyleElement.json` expose `api.HTMLStyleElement.sheet`.  The `load()` function loads the data from the first file, and then when it gets to the second file, notices that we already have a `sheet` member inside of `api.HTMLStyleElement`, so it [performs a recursive `extend()`](https://github.com/mdn/browser-compat-data/blob/71a3bca95a9cf385d2d73365c1cc26f8e93d0f5c/index.js#L48) through the feature.  That is, until it gets to the `mdn_url` member, which it attempts to perform a recursive `extend()` upon, but since it throws an error if either variable isn't a plain object (and `mdn_url`'s value is a string), the whole function crashes.

Now of course, we wouldn't want to have duplicate data anyways, and should probably have some sort of linter or otherwise to prevent it.  However, an error message such as the one we're getting is just plain unhelpful in figuring out what exactly is going on.

### PR DESCRIPTION
**Pull request by queengooborg**
In `index.js`, an error is thrown when attempting to run the `extend()` function on non-objects.  This error also unintentionally catches duplicate entries found in BCD, when attempting to merge their `mdn_url` properties.

However, in the context of duplicate entries, the error message is unhelpful at best.  It is not clear to the contributor that this means a feature's compat data was found twice in BCD.  This PR attempts to resolve that by throwing a more helpful error, stating that a duplicate entry was found.

Fixes #10734.

## Steps to replicate issue

1. Copy the JSON for `api.Document.copy_event` (the entire section) in `api/Document.json`
2. Paste it into a mixins file pertaining to Document, say `api/_mixins/DocumentOrShadowRoot__Document.json`, within `api.Document` (ex. right after line 3).  (Do not paste it into the same file.)

Before this PR, an error reading "Both target and source must be plain objects" will throw.  This PR will instead throw an error that reads "api.Document.copy_event was found twice! Please remove duplicate entries."

Before:
```
> @mdn/browser-compat-data@4.1.13 lint /Users/queengooborg/Developer/Gooborg/browser-compat-data
> node test/lint

/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:48
    throw new Error('Both target and source must be plain objects');
    ^

Error: Both target and source must be plain objects
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:48:11)
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:55:7)
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:55:7)
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:55:7)
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:55:7)
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:55:7)
    at processFilename (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:31:5)
    at Array.forEach (<anonymous>)
    at load (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:36:25)
    at Object.<anonymous> (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:62:18)
```

After:
```
> @mdn/browser-compat-data@4.1.13 lint /Users/queengooborg/Developer/Gooborg/browser-compat-data
> node test/lint

/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:57
        throw new Error(
        ^

Error: api.Document.copy_event was found twice! Please remove duplicate entries.
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:57:15)
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:61:7)
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:61:7)
    at extend (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:61:7)
    at processFilename (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:31:5)
    at Array.forEach (<anonymous>)
    at load (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:36:25)
    at Object.<anonymous> (/Users/queengooborg/Developer/Gooborg/browser-compat-data/index.js:68:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

### CODE REVIEW

**Comment by queengooborg** [comment]
I opened this PR after running into the error message whilst working on both #15480 and #15477.  In those PRs, I did a mass conversion of event handlers (`onfoo`) to events (`foo_event`), and I knew there would be some duplicate entries to work out.  However, with the `extend()` function the way it is now, I didn't have an easy way to find the duplicated features as I had no clue _which_ feature was duplicated.  So, during the first of the PRs, I wrote this tweak to nail down which feature was causing problems, thus eliminate the duplicate much quicker.

I updated the PR description to include a "steps to reproduce" section as well!

**Review by lucalves — APPROVED** [review]

File: index.js [hunk 1]
```diff
@@ -52,7 +52,13 @@ function extend(target, source) {
   for (const [key, value] of Object.entries(source)) {
     // recursively extend if target has the same key, otherwise just assign
     if (Object.prototype.hasOwnProperty.call(target, key)) {
-      extend(target[key], value);
+      if (key == '__compat') {
+        // If attempting to merge __compat, we have a double-entry
+        throw new Error(
```
Comment (ddbeck) [inline index.js:57]: It might be nice to subclass `Error` (e.g., `DuplicateCompatError`) instead of throwing a generic `Error`.

**Review by ddbeck — CHANGES_REQUESTED** [review]
OK, having had another look at this, a suggestion in a line comment.

Also, can you please include an actual before and after traceback in this issue? It'll serve as documentation for what changed and make it easier for other reviewers to understand what you're trying to achieve here.

File: index.js [hunk 2]
```diff
@@ -2,6 +2,13 @@
 const fs = require('fs');
 const path = require('path');
 
+class DuplicateCompatError extends Error {
+  constructor(message) {
+    super(message);
```
Comment (ddbeck) [inline index.js:7]: Error text suggestions:

- Put the message text template in the constructor, so it's not possible to have inconsistent message text (should this ever be reused elsewhere)
- Avoid "please" in the case of operator error ([example style guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/please))
- The count's not knowable here (there could be a third as-yet-unprocessed duplicate)

```suggestion
    super(`${feature} already exists! Remove duplicate entries.`);
```

File: index.js [hunk 3]
```diff
@@ -52,7 +59,13 @@ function extend(target, source) {
   for (const [key, value] of Object.entries(source)) {
     // recursively extend if target has the same key, otherwise just assign
     if (Object.prototype.hasOwnProperty.call(target, key)) {
-      extend(target[key], value);
+      if (key == '__compat') {
+        // If attempting to merge __compat, we have a double-entry
+        throw new DuplicateCompatError(
+          `${feature} was found twice! Please remove duplicate entries.`,
+        );
```
Comment (ddbeck) [inline index.js:66]:
```suggestion
        throw new DuplicateCompatError(feature);
```

**Review by ddbeck — CHANGES_REQUESTED** [review]
A couple more suggestions for you

**Review by ddbeck — APPROVED** [review]
Thank you! 🎉
