### PR TITLE
Add fix script to fix property order

### LINKED ISSUE #3505: Linter: Enforce more property sorting
In https://github.com/mdn/browser-compat-data/pull/3469#discussion_r258951255 @chrisdavidmills mentions that the properties in support objects should rather be sorted. Currently this can occur:
```json
{
  "version_removed": "7.0",
  "prefix": "webkit",
  "version_added": true
}
```
Desired would be:

```json
{
  "prefix": "webkit",
  "version_added": true,
  "version_removed": "7.0"
}
```

Instead of asking people to do that in reviews, the linter should enforce this style.

### PR DESCRIPTION
**Pull request by queengooborg**
This PR introduces a script that will fix the property order of properties within __compat statements to ensure consistency.  This is the first of three PRs as a part of migration 008.  Fixes #3505.

### CODE REVIEW

File: scripts/fix/property-order.js [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+function doOrder(value, order) {
+  return order.reduce((result, key) => {
+    if (key in value) result[key] = value[key];
+    return result;
+  }, {});
+}
+
+/**
+ * Return a new feature object whose first-level properties have been
+ * ordered according to Array.prototype.sort, and so will be
```
Comment (foolip) [inline scripts/fix/property-order.js:31]: No `sort()` call is involved here. The properties are sorted according to `propOrder`.

**Review by foolip — APPROVED** [review]
