### PR TITLE
Check for invalid combinations of `version_added` and `version_removed`

### LINKED ISSUE #1328: Check for invalid combinations of version_added and version_removed
There are features that were added in an unknown version, but that were removed at a known version.  The correct way to code this is ``version_added: true``, and ``version_removed`` as the version. Alternate versions, with ``version_added`` set to ``null`` or ``false``, should be flagged at pull request time, either as a schema violation or other linting exception.

The MediaStream API is a good example:

* https://developer.mozilla.org/en-US/docs/Web/API/MediaStream#Browser_compatibility
* https://github.com/mdn/browser-compat-data/blob/master/api/MediaStream.json

The correct way to encode this is ``version_added`` as ``true`` (supported in unknown version), and ``version_removed`` as the version removed, such as Chrome's support for ``ended``:

https://github.com/mdn/browser-compat-data/blob/5168b1fb947501af49bae3b36d7aa5d4cb52979f/api/MediaStream.json#L167-L171

chrome ended

This file has two alternate encodings that should be found before merging. Opera's support for ``id`` is set to ``version_added: null``, for unknown support, but ``version_removed: 39``:

https://github.com/mdn/browser-compat-data/blob/5168b1fb947501af49bae3b36d7aa5d4cb52979f/api/MediaStream.json#L254-L257

opera null

The second is Chrome's support for ``label``, where ``version_added: false`` is used for no support:

https://github.com/mdn/browser-compat-data/blob/5168b1fb947501af49bae3b36d7aa5d4cb52979f/api/MediaStream.json#L773-L777

chrome label false

We can fix this with a follow-on PR, but this will reduce the reviewer and contributor burden to automate the flagging of the problem.

First discussed [on Discourse](https://discourse.mozilla.org/t/bug-in-new-compat-data/26398/5) by me and @mec

### PR DESCRIPTION
**Pull request by ExE-Boss**
Resolves #1328

### CODE REVIEW

**Comment by MatonAnthony** [comment]
Looks good to me.

File: test/test-versions.js [hunk 1]
```diff
@@ -40,6 +40,13 @@ function testVersions(dataFilename) {
             console.error('  Valid ' + browser + ' versions are: ' + validBrowserVersions[browser].join(', '));
             hasErrors = true;
           }
+          if ("version_removed" in statement && "version_added" in statement) {
+            if (typeof statement.version_added !== "string" && statement.version_added !== true) {
+              console.error('\x1b[31m  version_added: "' + statement.version_added + '" is not a valid version number when version_removed is present');
+              console.error('  Valid ' + browser + ' versions are: ' + validBrowserVersions[browser].join(', '));
```
Comment (jwhitlock) [inline test/test-versions.js]: Can you add ``true`` to the front of the valid versions list?

File: test/test-versions.js [hunk 2]
```diff
@@ -40,6 +40,13 @@ function testVersions(dataFilename) {
             console.error('  Valid ' + browser + ' versions are: ' + validBrowserVersions[browser].join(', '));
             hasErrors = true;
           }
+          if ("version_removed" in statement && "version_added" in statement) {
+            if (typeof statement.version_added !== "string" && statement.version_added !== true) {
+              console.error('\x1b[31m  version_added: "' + statement.version_added + '" is not a valid version number when version_removed is present');
+              console.error('  Valid', browser, 'versions are:', validBrowserVersions[browser].length > 0 ? 'true, ' + validBrowserVersions[browser].join(', ') : 'true');
```
Comment (jwhitlock) [inline test/test-versions.js]: Very clever! I wasn't thinking of the "no valid versions" case. 😄
